# [ 현재 디렉토리 경로와 Keras 버전 확인하기 ]

In [1]:
import os
import keras

current_directory = os.getcwd()
print("Current Directory Path : {}".format(current_directory))

current_version = keras.__version__
print("Current Keras Version : {}".format(current_version))

AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'

# [ STM32Cube.AI 에서 지원하는 Keras Vesrion 설치하기 ]


In [6]:
# STM32Cube.AI에서 지원하는 Keras Version으로 변겯하기.
!pip install tensorflow==2.11.0 keras==2.11.0

  Using cached keras-2.11.0-py2.py3-none-any.whl.metadata (1.4 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 759.7 kB/s eta 0:00:00
Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 87.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 30.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 93.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 43.6 MB/s eta 0:00:00
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninst

In [1]:
import os
import tensorflow as tf

current_directory = os.getcwd()
print("Current Directory Path : {}".format(current_directory))

current_version = tf.keras.__version__
print("Current Keras Version : {}".format(current_version))

Current Directory Path : /content
Current Keras Version : 2.11.0


# [ Iris Dataset 불러오기 ]

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Iris dataset 불러오기, Iris.csv 불러오기
iris_data = pd.read_csv('iris.csv')

# Iris.csv에서 Feature와 Label로 구분하기
total = iris_data.iloc[:, ].values
x = iris_data.iloc[:, :-1].values
y = iris_data.iloc[:, -1].values

#print(total)
#print("Feature data shape : {} \n{}".format(x.shape, x))

# Encode the class labels into numeric categorical values
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_onehot = to_categorical(y_encoded)
print("One hot Encoding Result Shape : {} \n{}".format(y_onehot.shape, y_onehot))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y_onehot, test_size=0.2, random_state=42)

#print("X_train number : {}, X_test number : {}, y_train : {}, y_test : {}".format(X_train.size, X_test.size, y_train.size, y_test.size))
#print("X_train Shape : {}, X_test : {}, y_train : {}, y_test : {}".format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))


One hot Encoding Result Shape : (149, 3) 
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

# [ Model 생성하기 ]

In [5]:
# Build the Keras model

# input_shape로 모델 재구성
model = Sequential([
    Dense(10, input_shape=(4,), activation='relu'), # Input layer 10 units and activation : relu
    Dense(8, activation='relu'), # Hidden layer 8 units and activation : relu
    Dense(3, activation='softmax') # Output layer 3 units and activation : softmax (3classes)
])

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=5, verbose=1)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

# 학습된 모델을 .h5 파일로 저장
model.save("Fully_Connected_Iris.h5")


Epoch 1/100
24/24 [==============================] - 1s 2ms/step - loss: 1.2587 - accuracy: 0.3361 
Epoch 2/100
24/24 [==============================] - 0s 2ms/step - loss: 1.0975 - accuracy: 0.4706
Epoch 3/100
24/24 [==============================] - 0s 2ms/step - loss: 0.9967 - accuracy: 0.6387
Epoch 4/100
24/24 [==============================] - 0s 2ms/step - loss: 0.9297 - accuracy: 0.6555
Epoch 5/100
24/24 [==============================] - 0s 2ms/step - loss: 0.8783 - accuracy: 0.6555
Epoch 6/100
24/24 [==============================] - 0s 2ms/step - loss: 0.8265 - accuracy: 0.6555
Epoch 7/100
24/24 [==============================] - 0s 2ms/step - loss: 0.7790 - accuracy: 0.6555
Epoch 8/100
24/24 [==============================] - 0s 2ms/step - loss: 0.7280 - accuracy: 0.6891
Epoch 9/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6821 - accuracy: 0.7059
Epoch 10/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6435 - accuracy: 0.6555
Epoch 11

# [ Model 불러오기 ]

In [8]:
from tensorflow.keras.models import load_model
import tensorflow as tf

# Load the pre-trained model
model = load_model('Fully_Connected_Iris.h5')
model.summary()

input_shape = model.input_shape
print("Input shape:", input_shape)

# Make predictions on new data
X_new_data = np.array([[5.1, 3.5, 1.4, 0.2],  # Example data point 1
                       [6.3, 3.3, 6.0, 2.5],
                       [6.6, 2.9, 4.6, 1.3]])  # Example data point 2

predictions = model.predict(X_new_data)
predicted_classes = np.argmax(predictions, axis=1)

print("Results of predictions")
print(predictions)
print(predicted_classes)

# Decode the numeric predictions back to original class labels
predicted_labels = encoder.inverse_transform(predicted_classes)
print(predicted_labels)

print(X_new_data.shape)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                50        
                                                                 
 dense_4 (Dense)             (None, 8)                 88        
                                                                 
 dense_5 (Dense)             (None, 3)                 27        
                                                                 
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________
Input shape: (None, 4)
1/1 [==============================] - 0s 91ms/step
Results of predictions
[[9.99208868e-01 4.55629604e-04 3.35497229e-04]
 [9.86155328e-07 3.73836863e-03 9.96260583e-01]
 [1.11161746e-04 9.51450944e-01 4.84379642e-02]]
[0 2 1]
['Iris-setosa' 'Iris-virginica' 'Iris-versicolor']
(3, 4)
