# [ 현재 디렉토리 경로와 Keras 버전 확인하기 ]

In [1]:
import os
import keras

current_directory = os.getcwd()
print("Current Directory Path : {}".format(current_directory))

current_version = keras.__version__
print("Current Keras Version : {}".format(current_version))

Current Directory Path : /content
Current Keras Version : 2.11.0


# [ STM32Cube.AI 에서 지원하는 Keras Vesrion 설치하기 ]


In [2]:
# STM32Cube.AI에서 지원하는 Keras Version으로 변겯하기.
!pip install keras==2.11.0


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.6 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.


# [ Iris Dataset 불러오기 ]

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

# Iris dataset 불러오기, Iris.csv 불러오기
iris_data = pd.read_csv('iris.csv')

# Iris.csv에서 Feature와 Label로 구분하기
total = iris_data.iloc[:, ].values
x = iris_data.iloc[:, :-1].values
y = iris_data.iloc[:, -1].values

#print(total)
#print("Feature data shape : {} \n{}".format(x.shape, x))

# Encode the class labels into numeric categorical values
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_onehot = np_utils.to_categorical(y_encoded)

print("One hot Encoding Result Shape : {} \n{}".format(y_onehot.shape, y_onehot))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y_onehot, test_size=0.2, random_state=42)

#print("X_train number : {}, X_test number : {}, y_train : {}, y_test : {}".format(X_train.size, X_test.size, y_train.size, y_test.size))
#print("X_train Shape : {}, X_test : {}, y_train : {}, y_test : {}".format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))


One hot Encoding Result Shape : (149, 3) 
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

# [ Model 생성하기 ]

In [3]:
# Build the Keras model
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='relu'))  # Input layer 10 units and activation : relu
model.add(Dense(8, activation='relu'))  # Hidden layer 8 units and activation : relu
model.add(Dense(3, activation='softmax'))  # Output layer 3 units and activation : softmax (3classes)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=5, verbose=1)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

# 학습된 모델을 .h5 파일로 저장
model.save("Fully_Connected_Iris.h5")


Epoch 1/100
24/24 [==============================] - 2s 6ms/step - loss: 1.2475 - accuracy: 0.1008
Epoch 2/100
24/24 [==============================] - 0s 5ms/step - loss: 1.0855 - accuracy: 0.5210
Epoch 3/100
24/24 [==============================] - 0s 4ms/step - loss: 1.0313 - accuracy: 0.5630
Epoch 4/100
24/24 [==============================] - 0s 4ms/step - loss: 0.9837 - accuracy: 0.6050
Epoch 5/100
24/24 [==============================] - 0s 9ms/step - loss: 0.9477 - accuracy: 0.6134
Epoch 6/100
24/24 [==============================] - 0s 4ms/step - loss: 0.9110 - accuracy: 0.5210
Epoch 7/100
24/24 [==============================] - 0s 4ms/step - loss: 0.8632 - accuracy: 0.5966
Epoch 8/100
24/24 [==============================] - 0s 4ms/step - loss: 0.8231 - accuracy: 0.6471
Epoch 9/100
24/24 [==============================] - 0s 5ms/step - loss: 0.7888 - accuracy: 0.7311
Epoch 10/100
24/24 [==============================] - 0s 4ms/step - loss: 0.7480 - accuracy: 0.9160
Epoch 11/

# [ Model 불러오기 ]

In [7]:
from keras.models import load_model
import tensorflow as tf

# Load the pre-trained model
model = load_model('Fully_Connected_Iris.h5')
model.summary()

input_shape = model.layers[0].input_shape
print("Input shape:", input_shape)

# Make predictions on new data
X_new_data = np.array([[5.1, 3.5, 1.4, 0.2],  # Example data point 1
                       [6.3, 3.3, 6.0, 2.5],
                       [6.6, 2.9, 4.6, 1.3]])  # Example data point 2

predictions = model.predict(X_new_data)
predicted_classes = np.argmax(predictions, axis=1)

print("Results of predictions")
print(predictions)
print(predicted_classes)

# Decode the numeric predictions back to original class labels
predicted_labels = encoder.inverse_transform(predicted_classes)
print(predicted_labels)

print(X_new_data.shape)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                50        
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________
Input shape: (None, 4)
1/1 [==============================] - 0s 98ms/step
Results of predictions
[[9.9939620e-01 6.0358323e-04 1.9717277e-07]
 [2.8483450e-07 1.9596760e-04 9.9980372e-01]
 [1.1188523e-03 9.9721032e-01 1.6707559e-03]]
[0 2 1]
['Iris-setosa' 'Iris-virginica' 'Iris-versicolor']
(3, 4)
