# [ 현재 디렉토리 경로와 Keras 버전 확인하기 ]

In [1]:
import os
import keras

current_directory = os.getcwd()
print("Current Directory Path : {}".format(current_directory))

current_version = keras.__version__
print("Current Keras Version : {}".format(current_version))

Current Directory Path : /content
Current Keras Version : 3.4.1


# [ STM32Cube.AI 에서 지원하는 Keras Vesrion 설치하기 ]


In [2]:
# STM32Cube.AI에서 지원하는 Keras Version으로 변겯하기.
!pip install keras==2.11.0


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 34.6 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 3.4.1
    Uninstalling keras-3.4.1:
      Successfully uninstalled keras-3.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.17.0 requires keras>=3.2.0, but you have keras 2.11.0 which is incompatible.


In [2]:
!pip install --upgrade tensorflow keras

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.3/615.3 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 47.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 39.3 MB/s eta 0:00:00
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.0
    Uninstalling tensorboard-2.17.0:
      Successfully uninstalled tensorboard-2.17.0
  Attempting uninstall: keras
    Found existing installation: keras 2.11.0
    Uninstalling keras-2.11.0:
      Successfully uninstalled keras-2.11.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.17.0
    Uninstalling tensorflow-2.17.0:
      Successfully uninstalled tensorflow-2.17.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.18.0 which is incom

# [ Iris Dataset 불러오기 ]

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Iris dataset 불러오기, Iris.csv 불러오기
iris_data = pd.read_csv('iris.csv')

# Iris.csv에서 Feature와 Label로 구분하기
total = iris_data.iloc[:, ].values
x = iris_data.iloc[:, :-1].values
y = iris_data.iloc[:, -1].values

#print(total)
#print("Feature data shape : {} \n{}".format(x.shape, x))

# Encode the class labels into numeric categorical values
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_onehot = to_categorical(y_encoded)
print("One hot Encoding Result Shape : {} \n{}".format(y_onehot.shape, y_onehot))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y_onehot, test_size=0.2, random_state=42)

#print("X_train number : {}, X_test number : {}, y_train : {}, y_test : {}".format(X_train.size, X_test.size, y_train.size, y_test.size))
#print("X_train Shape : {}, X_test : {}, y_train : {}, y_test : {}".format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))


# [ Model 생성하기 ]

In [3]:
# Build the Keras model
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='relu'))  # Input layer 10 units and activation : relu
model.add(Dense(8, activation='relu'))  # Hidden layer 8 units and activation : relu
model.add(Dense(3, activation='softmax'))  # Output layer 3 units and activation : softmax (3classes)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=5, verbose=1)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

# 학습된 모델을 .h5 파일로 저장
model.save("Fully_Connected_Iris.h5")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2967 - loss: 2.4810
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3248 - loss: 1.7420  
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4109 - loss: 1.1577
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6498 - loss: 0.9052
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7297 - loss: 0.6569
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6618 - loss: 0.6641 
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5678 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.5727
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7375 - loss: 0.4789
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7483 - loss: 0.4704
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7072 - loss: 0.5023
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accur

Test loss: 0.1460, Test accuracy: 0.9333


# [ Model 불러오기 ]

In [5]:
from tensorflow.keras.models import load_model
import tensorflow as tf

# Load the pre-trained model
model = load_model('Fully_Connected_Iris.h5')
model.summary()

input_shape = model.input_shape
print("Input shape:", input_shape)

# Make predictions on new data
X_new_data = np.array([[5.1, 3.5, 1.4, 0.2],  # Example data point 1
                       [6.3, 3.3, 6.0, 2.5],
                       [6.6, 2.9, 4.6, 1.3]])  # Example data point 2

predictions = model.predict(X_new_data)
predicted_classes = np.argmax(predictions, axis=1)

print("Results of predictions")
print(predictions)
print(predicted_classes)

# Decode the numeric predictions back to original class labels
predicted_labels = encoder.inverse_transform(predicted_classes)
print(predicted_labels)

print(X_new_data.shape)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 167 (672.00 B)

 Trainable params: 165 (660.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

Input shape: (None, 4)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
Results of predictions
[[9.9922037e-01 7.7958032e-04 5.8269619e-14]
 [4.5881723e-08 5.5248719e-03 9.9447507e-01]
 [7.1877573e-04 9.9381846e-01 5.4627261e-03]]
[0 2 1]
['Iris-setosa' 'Iris-virginica' 'Iris-versicolor']
(3, 4)
